HelloWorld/polls/urls.py
# -*- coding:utf-8 -*-

from django.urls import path
from . import views
from django.views.generic import TemplateView,RedirectView

app_name = 'polls' # for Django differentiate the URL names between apps

urlpatterns = [
    
    path('aboutus/',TemplateView.as_view(template_name='polls/about.html'),name='aboutus'),# 直接用TemplateView,无需在views中定义class
    path('about/',views.AboutView.as_view(),name='about'),# 定义class方式使用TemplateView
    
    path('go-to-RedirectView/',RedirectView.as_view(url='https://docs.djangoproject.com/en/2.2/ref/class-based-views/base/#django.views.generic.base.RedirectView'),name='go-to-RedirectView'),
    
    path('',views.index,name='index'), # name不要忘了！！！
    path('index1/',views.IndexView1.as_view(),name='index1'),# ListView
    path('index2/',views.IndexView2.as_view(),name='index2'),# TemplateView
    
    #path('<slug:slug>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),          # DetailView
    path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),# DetailView
    
    path('<int:question_id>/vote/',views.vote,name='vote'),# /polls/5/vote/
    
]

HelloWorld/polls/models.py
# -*- coding:utf-8 -*-

from django.db import models
# from django.utils.text import slugify

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')
#     slug = models.SlugField(max_length=50)
#     def save(self, *args, **kwargs):
#         self.slug = slugify(self.question_text)
#         super(Question, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.question_text
    
class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
    

HelloWorld/HelloWorld/views.py
# -*- coding:utf-8 -*-

from django.http import HttpResponse

def hello(request):
    return HttpResponse("Hello,world.")

HelloWorld/polls/views.py
# -*- coding:utf-8 -*-

from django.shortcuts import render,get_object_or_404
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
#from django.views.generic import TemplateView
from .models import Question,Choice
from django.utils import timezone
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage,InvalidPage


# Create your views here.

'''
关于：使用 TemplateView
'''
class AboutView(generic.TemplateView):
    template_name = 'polls/about.html'

'''
显示问题及选项：使用 DetailView
'''
class DetailView(generic.DetailView):
    #template_name = 'polls/detail.html' # 不指定则自动找默认规则的页面 <model name>_detail.html。By default, the DetailView generic view uses a template called <app name>/<model name>_detail.html.
    model = Question # 必须指定model，对应的question将自动作为context字典的一部分。
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vote_time'] = timezone.now() # override default context,and append your own elements in it.
        return context

# def detail(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,'polls/detail.html',{'question':question})
#     #return HttpResponse("Question %s" %question_id)

'''
查看投票结果
'''
class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'# 如果这里不指定，则默认为question_detail.html,参见上面的DetailView实现。
    model = Question
    
# def results(request,question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     return render(request,'polls/results.html',{'question':question})
#     #return HttpResponse("The results of question %s" %question_id)


'''
首页，列表显示投票问题：使用 ListView
'''
class IndexView1(generic.ListView):
    template_name = 'polls/index.html' # the ListView generic view uses a default template called <app name>/<model name>_list.html
    context_object_name = 'latest_question_list' #默认为 <model name>_list，或直引用 object_list，这里override默认变量
    #all_list = Question.objects.order_by('-pub_date')
    def get_queryset(self):
        all_list = Question.objects.order_by('pub_date')
        return all_list #返回的all_list对象在页面中以context_object_name变量定义的名称访问
    

'''
首页，列表显示投票问题：使用 TemplateView （效果同上面的 ListView,实际上ListView继承自TemplateView）
'''
class IndexView2(generic.TemplateView):
    template_name = 'polls/index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_question_list'] = Question.objects.order_by('-pub_date')[:3]
        return context
    
def index(request):
    #return HttpResponse("Hello,world.You're at the polls index.")
    question_list = Question.objects.order_by('pub_date')
    #latest_question_list = Question.objects.filter(question_text__icontains='what').order_by('-pub_date')[:5] # 模糊查询，按时间倒序取前5
    paginator = Paginator(question_list,3)
    #print(paginator.num_pages)
    page = request.GET.get('page')
    #     try:
    #         latest_question_list = paginator.page(page)
    #     except (PageNotAnInteger,InvalidPage):
    #         latest_question_list = paginator.page(1)
    #     except EmptyPage:
    #         latest_question_list = paginator.page(paginator.num_pages)
    latest_question_list = paginator.get_page(page) #异常时自动首页或末页，get_page与page方法的区别
    
    return render(request,'polls/index.html',{'latest_question_list':latest_question_list})


'''
投票并记录
'''
def vote(request,question_id):
    #return HttpResponse("Voting question %s" %question_id)
    question = get_object_or_404(Question,pk=question_id)
    try:
        # print('try 111')
        selected_choice = question.choice_set.get(pk=request.POST['choice']) 
        # selected_choice = question.choice_set.get(pk=request.POST.get('choice'))  # 效果同上，还可以提供默认值 .get('choice','1') 即：choice.id=1 
        # selected_choice = get_object_or_404(Choice,pk=request.POST.get('choice')) # 效果同上，直接get object可以
        # print('try 222')
    except KeyError:
        return render(request, 'polls/question_detail.html', {'question':question,'error_message':'您没有选择！'})
    except Choice.DoesNotExist:
        return render(request, 'polls/question_detail.html', {'question':question,'error_message':'您没有选择！！'})
    else:
        # selected_choice.votes += 1
        # Another useful benefit of F() is that having the database - rather than Python - update a field’s value avoids a race condition.
        # it will only ever update the field based on the value of the field in the database when the save() or update() is executed, rather than based on its value when the instance was retrieved.
        selected_choice.votes = F('votes') + 1 # Avoiding race conditions using F()，直接在DB层面修改数据，不读到内在中。详见：Python Query Expressions
        selected_choice.save()
        
        # F() objects assigned to model fields persist after saving the model instance and will be applied on each save(). For example:
        #selected_choice.choice_text = 'C语言'
        #selected_choice.save() # 不仅修改choice_text，还会把votes再加1
        
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,))) # Reverse function helps avoid having to hardcode a URL in the view function
        '''
                 注意！！！调试时总出错的原因是这里的   polls:results 错误地写成了 polls:vote，导致再次进入此方法而未提供question_id，出现Choice.DoesNotExist异常！
         Always return an HttpResponseRedirect after successfully dealing with POST data. This prevents data from being posted twice if a user hits the Back button.
                 在python中访问一个页面的几种方法：（代码中、页面中）
         1.return HttpResponse("The results of question %s" %question_id) ，                      直接response页面内容
         2.return render(request,'polls/results.html',{'question':question}) ，                直接render目标templates页面并传递context参数
         3.return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))，  按照urls中定义的path访问对应的view方法并传递path中定义的参数（有别于request参数）
         4.<a href="{% url 'polls:detail' question.id %}">，                           同3.
         5.<form action="{% url 'polls:vote' question.id %}" method="post">            同4.
        '''
        


HelloWorld/polls/templates/polls/about.html
<p>This is aboutus/about page.</p>
<p>Use TemplateView,no model.</p>

HelloWorld/polls/templates/polls/index.html
<!-- {% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<!- -<li><a href="/polls/{{question.id}}">{{question.question_text}}</a></li>- ->
			<h2><li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li></h2>
		{% endfor %}
	</ul>
{% else %}
	<p>没有polls记录！</p>
{% endif %} -->


<ul>
{% for question in latest_question_list %}
    <h2><li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li></h2>
{% empty %} <!-- 省去了if else语句的判断 -->
    <li>没有polls记录！</li>
{% endfor %}
</ul>

<div class="pagination">
    <span class="step-links"><ul>
        {% if latest_question_list.has_previous %}
            <a href="?page=1">&laquo; 首页</a>
            <a href="?page={{ latest_question_list.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            {{ latest_question_list.number }}/{{ latest_question_list.paginator.num_pages }}
        </span>

        {% if latest_question_list.has_next %}
            <a href="?page={{ latest_question_list.next_page_number }}">下一页</a>
            <a href="?page={{ latest_question_list.paginator.num_pages }}">末页 &raquo;</a>
        {% endif %}</ul>
    </span>
</div>

<br>

<p><a href="{% url 'polls:aboutus' %}">Aboutus</a> | <a href="{% url 'polls:about' %}">About</a> | <a href="{% url 'polls:go-to-RedirectView' %}">Go-to-RedirectView</a></p>


HelloWorld/polls/templates/polls/question_detail.html
<h2>{{ question.question_text }}</h2>
<!-- DetailView方式下，object自动对应model定义的question（自动包含在context中），但如果不是generic view方式，则object为空 -->

{% if error_message %}
	<p><strong><font color="red">{{ error_message }}</font></strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<p><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label></p>
	{% endfor %}
	<br><input type="submit" value="投一票">&nbsp;{{ vote_time }} <!-- context中自定义添加的元素 -->
</form>

HelloWorld/polls/templates/polls/results.html
<h2>{{ question.question_text }}</h2>

{% for choice in question.choice_set.all %}
	<p>{{ choice.choice_text }} --- {{ choice.votes }} vote{{ choice.votes|pluralize }}</p>
	<!-- 使用形式：{{value | pluralize}}，或者{{value | pluralize:"es"}}，或者{{value | pluralize:"y,ies"}}意义：如果value不是1，则返回一个复数后缀，缺省的后缀是's' -->
{% endfor %}
</ul><p><a href="{% url 'polls:detail' question.id %}">再投一次</a> | <a href="{% url 'polls:index' %}">返回首页</a> | <a href="{% url 'polls:index1' %}">返回首页1</a> | <a href="{% url 'polls:index2' %}">返回首页2</a></p>